// Auth reducers
export const LOGOUT = 'LOGOUT';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GET_MERCHANT = 'GET_MERCHANT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

// Add product reducers
export const SET_SKU = 'SET_SKU';
export const SET_SHARED = 'SET_SHARED';
export const CLEAR_STATE = 'CLEAR_STATE';
export const SET_TAX_RULE = 'SET_TAX_RULE';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_IMAGE_DATA = 'SET_IMAGE_DATA';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const SET_CHECK_STORE = 'SET_CHECK_STORE';
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS';
export const SET_CHECK_SHARED = 'SET_CHECK_SHARED';
export const SET_PRODUCT_NAME = 'SET_PRODUCT_NAME';
export const SET_TAX_INC_PRICE = 'SET_TAX_INC_PRICE';
export const SET_TAX_EXC_PRICE = 'SET_TAX_EXC_PRICE';
export const SET_TOTAL_QUANTITY = 'SET_TOTAL_QUANTITY';
export const SET_ACCESS_PERCENT = 'SET_ACCESS_PERCENT';
export const SET_CHECK_SHARE_ALL = 'SET_CHECK_SHARE_ALL';
export const SET_SHARED_MERCHANTS = 'SET_SHARED_MERCHANTS';
export const SET_CHECK_SHARE_UNITS = 'SET_CHECK_SHARE_UNITS';
export const SET_CHECK_SHARE_AMOUNT = 'SET_CHECK_SHARE_AMOUNT';
export const SET_CHECK_SHARE_PERCENT = 'SET_CHECK_SHARE_PERCENT';
export const SET_CHECK_STORE_INVENTORY = 'SET_CHECK_STORE_INVENTORY';
export const SET_CHECK_QUANTITY_FINITE = 'SET_CHECK_QUANTITY_FINITE';
export const SET_CHECK_SHARED_INVENTORY = 'SET_CHECK_SHARED_INVENTORY';
export const SET_CHECK_QUANTITY_INFIFNITE = 'SET_CHECK_QUANTITY_INFIFNITE';
export const SET_CHECK_TAX_ON = 'SET_CHECK_TAX_ON';
export const SET_CHECK_TAX_OFF = 'SET_CHECK_TAX_OFF';

export const SET_STATE_TAX = 'SET_STATE_TAX';
export const SET_CCOUNTY_TAX = 'SET_CCOUNTY_TAX';
export const SET_SPECIAL_DISTRICT_TAX = 'SET_SPECIAL_DISTRICT_TAX';
export const SET_MANAUL_TAX_RATE = 'SET_MANAUL_TAX_RATE';

export const SET_PRODUCT_WEIGHT = 'SET_PRODUCT_WEIGHT';
export const SET_PRODUCT_VOLUME = 'SET_PRODUCT_VOLUME';
export const SET_PRODUCT_LENGTH = 'SET_PRODUCT_LENGTH';
export const SET_PRODUCT_HEIGHT = 'SET_PRODUCT_HEIGHT';
export const SET_PRODUCT_WIDTH = 'SET_PRODUCT_WIDTH';
